# Site settings
title: "Mi prueba web Jekyll"
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/testjuan" # the subpath of your site, e.g. /blog/
url: "https://juandagaa.github.io/testjuan" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
